### PR TITLE
Trunk

### PR DESCRIPTION
**Pull request by CuriousCurmudgeon**
I would like to start getting some feedback on integrating this back into the main trunk. Here is what I have.
- New batch modify module.
- Batch modify UI integrated into query page.
- New permission (TICKET_BATCH_MODIFY)
- Added a new page to the TracGuide and updated the TOC macro.
- Wrote tests against new module.

I still have a couple of outstanding issues as well.
- One of the new batch tests fails. Right now I think the problem is with the test itself. I cannot reproduce the error through a running Trac instance. I'm probably doing something wrong with the EnvironmentStub.
- I don't have any tests on my query page integration. Are there any examples of permission testing I can look at? I want to test that batch data is only added when the user has the appropriate permission.
- The documentation page I added to the wiki feels off. I don't feel like I'm explaining the configuration options in a clean way. Suggestions welcome.

### CODE REVIEW

**Comment by CuriousCurmudgeon** [comment]
Also, this is my first time using Github. I'm assuming I don't need to filter the changes I've been merging in since my initial fork.

**Comment by coderanger** [comment]
This is just a mirror, any code changes will need to be submitted to the tracker on http://trac.edgewall.org./

**Comment by CuriousCurmudgeon** [comment]
Well aware. I have a proposal page [1] and a related ticket [2] already. I'm just looking for some discussion on my changes and felt it might be easier with the commits right here. I can start a thread on the dev list if preferred.

[1] http://trac.edgewall.org/wiki/TracDev/Proposals/BatchModification
[2] http://trac.edgewall.org/ticket/525

**Comment by coderanger** [comment]
That would probably be wise, not many of the Trac devs are even setup on the edgewall org here, and I think I might be the only one that uses github regularly enough to have noticed this req.

**Comment by coderanger** [comment]
Closing this request.

**Pull request closed without merging**
