### PR TITLE
[WIP] Add Python 3 compatibility with six

### PR DESCRIPTION
**Pull request by timgraham**
https://trac.edgewall.org/ticket/12130

### CODE REVIEW

**Comment by rjollos** [comment]
Before you spend too much time on this, I've proposed we do a hard cutover to Python 3.5+. The 2-3 compatibility adds too much complexity in my opinion and python2 is unsupported in 18 months.

**Comment by rjollos** [comment]
I'll raise the point on the mailing list later today and see if we can get agreement for dropping python2 in Trac 1.5.1.

**Comment by timgraham** [comment]
That's fine with me. I think I'd still use six as a stepping stone so that the tests keep passing on Python 2, then work to fix the Python 3 failures incrementally. For merging this, I can modify the commits and remove six usage -- many of the changes are still relevant.

**Review by rjollos — COMMENTED** [review]
It looks like 6363aa30 could be a pull request that is independent of the `six` module.

**Comment by timgraham** [comment]
I'm not going to continue this path anymore. Instead I'll work on writing Python 3-only code without six.

**Pull request closed without merging**
